# Generated by Django 3.2.25 on 2026-02-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0009_alter_message_eml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
