# Generated by Django 3.2.25 on 2026-03-11 01:21

from django.db import migrations, models
import django_mailbox.utils


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0010_auto_20260217_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='document',
            field=models.FileField(blank=True, upload_to=django_mailbox.utils.get_attachment_save_path, verbose_name='Document'),
        ),
    ]
