# Generated by Django 3.2.25 on 2026-03-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0011_messageattachment_document_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='uri',
            field=models.CharField(blank=True, default=None, help_text="Example: imap+ssl://myusername:mypassword@someserver <br /><br />Internet transports include 'imap' and 'pop3'; common local file transports include 'maildir', 'mbox', and less commonly 'babyl', 'mh', and 'mmdf'. <br /><br />Be sure to urlencode your username and password should they contain illegal characters (like @, :, etc).", max_length=500, null=True, verbose_name='URI'),
        ),
    ]
